MSG="String functionality test"
H_RULE="/*****************************************************************************/"
CC=g++

all: hello_print
	${CC} ../SString.cpp test.cpp -o stringTest.out

hello_print:
	@echo ${H_RULE}
	@echo ""
	@echo "      " ${MSG}
	@echo ""
	@echo ${H_RULE}


